Repository MrKrishnaAgarwal/Git-CheatSheet, pull requests merged in 2023-10, with the labels that each got.

#16 Added Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.yml
Labels: documentation, enhancement, good first issue, hacktoberfest

#19 added submodules and stash commands
  README.md
Labels: documentation, enhancement, hacktoberfest

#22 feat: added pre-commit
  .github/workflows /pre-commit.yml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 feat: added workflows and config
  .github/config.yml
  .github/workflows /pre-commit.yml
  .github/workflows/community.yml
  .github/workflows/pre-commit.yml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
